config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :work_mates
  resources :track_mates
  resources :works
  resources :tracks


  devise_for :designers, controllers: {
    registrations: 'designers/registrations'
  }
  devise_for :producers, controllers: {
    registrations: 'producers/registrations'
  }
  resources :designers do
    get :pending
    get :works
    get :requested
  end
  resources :producers do
    get :pending
    get :tracks
    get :requested
  end
  root 'home#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default container-fluid">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">Find Your Creative SoulMate</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-user-circle-o" style="font-size:24px"></i>
                    <span class="caret"></span>
                    </a>
            <ul class="dropdown-menu">
            <% if producer_signed_in? %>
                <li><%=link_to 'My Profile', edit_producer_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'Sign Out', destroy_producer_session_path, method: :delete %></li>
            <% elsif designer_signed_in? %>
                <li><%=link_to 'My Profile', edit_designer_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'Sign Out', destroy_designer_session_path, method: :delete %></li>
            <% else %>
                <li><%=link_to 'Sign In As Producer', new_producer_session_path %></li> 
                <li><%=link_to 'Sign In As Designer', new_designer_session_path %></li>          
                <li><%=link_to 'Sign Up As Producer', new_producer_registration_path %></li>
                <li><%=link_to 'Sign Up As Designer', new_designer_registration_path %></li>
            <% end %>

                </ul>
            </li>
            </ul>
        </div>
    </div>
</nav>

app/views/shared/_navbar2.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-secondary.bg-gradient">
    <div class="container-fluid">
    <%= link_to "Creative Soulmate", root_path, class: "navbar-brand" %>
    <%# <a class="navbar-brand" href="#">Creative SoulMate</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Access
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <% if producer_signed_in? %>
                <li><%=link_to 'My Profile', edit_producer_registration_path, class: "dropdown-item" %></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'My Tracks', producer_tracks_path(current_producer), class: "dropdown-item" %></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'My Pending SoulMates', producer_pending_path(current_producer), class: "dropdown-item" %></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'My Requested SoulMates', producer_requested_path(current_producer), class: "dropdown-item" %></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'Sign Out', destroy_producer_session_path, method: :delete, class: "dropdown-item" %></li>
            <% elsif designer_signed_in? %>
                <li><%=link_to 'My Profile', edit_designer_registration_path, class: "dropdown-item" %></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'My Works', designer_works_path(current_designer), class: "dropdown-item" %></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'My Pending SoulMates', designer_pending_path(current_designer), class: "dropdown-item" %></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'My Requested SoulMates', designer_requested_path(current_designer), class: "dropdown-item" %></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'Sign Out', destroy_designer_session_path, method: :delete, class: "dropdown-item" %></li>
            <% else %>
                <li><%=link_to 'Sign In As Producer', new_producer_session_path, class: "dropdown-item" %></li> 
                <li><%=link_to 'Sign In As Designer', new_designer_session_path, class: "dropdown-item" %></li>          
                <li><%=link_to 'Sign Up As Producer', new_producer_registration_path, class: "dropdown-item" %></li>
                <li><%=link_to 'Sign Up As Designer', new_designer_registration_path, class: "dropdown-item" %></li>
            <% end %>

            </ul>
        </li>
        </ul>
    </div>
    </div>
</nav>