config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :work_mates
  resources :track_mates
  resources :works
  resources :tracks


  devise_for :designers, controllers: {
    registrations: 'designers/registrations'
  }
  devise_for :producers, controllers: {
    registrations: 'producers/registrations'
  }
  resources :designers do
    get :pending
    get :works
    get :requested
  end
  resources :producers do
    get :pending
    get :tracks
    get :requested
  end
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:search] && (designer_signed_in? || producer_signed_in?)
      @class_name = designer_signed_in? ? 'Track' : 'Work'
      @search = @class_name.constantize.tagged_with(params[:search].split(' '))
      @opt = "#{@class_name.downcase}_name"
    end

    respond_to do |format|
      format.html
      format.js 
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_track.html.erb
<div class="card text-center">
    <div class="card-header">
        From: <%= s.producer %>
    </div>
    <div class="card-body">
        <h5 class="card-title"><%= s[@opt] %></h5>
        <audio id="player" controls>
        <source src="<%= url_for(s.file) %>" type="audio/mp3">
    </audio>
    <% if TrackMate.exists?(designer_id: current_designer.id, track_id: s.id) %>
        <p>Pending Request!</p>
    <% else %>
        <%= button_to "SoulMate!", track_mates_path(track_id: s.id, method: :post), class: "btn btn-primary" %>
    <% end %>
    </div>
    <div class="card-footer text-muted">
        <%= s.created_at %>
    </div>
    <div class="card-footer text-muted">
        <%= s.tag_list %>
    </div>
</div><br><br><br>

app/views/home/_work.html.erb
<div class="card">
    <div class="card-body">
        <h5 class="card-title"><%= s[@opt] %></h5>
        <p class="card-text">From: <%= s.designer %></p>
        <p class="card-text"><small class="text-muted"><%= s.created_at %></small></p>
    </div >
    <%= image_tag(s.file, width: "40%") %>
    <div class="card-body">
        <% if WorkMate.exists?(producer_id: current_producer.id, work_id: s.id) %>
            <p>Pending Request!</p>
        <% else %>
            <%= button_to "SoulMate!", work_mates_path(work_id: s.id, method: :post), class: "btn btn-primary" %>
        <% end %>
    <div class="card-footer text-muted">
        <%= s.tag_list %>
    </div>
    </div>
</div><br><br>

app/views/home/index.html.erb
<% if producer_signed_in? %>
    <div class="container text-center">
        <h1>Welcome <%= current_producer.name %></h1><br><br><br>
        <h4>Use the search bar to look for tags related to the works you are interested in</h4>
        <%= form_for(root_path, remote: true, method: :get) do %>
            <%= text_field_tag :search, params[:search], placeholder: "Enter tag term" %>
            <%= submit_tag "Search" %>
            <br><br>
        <% end %>
        <ul id="search-results"></ul>
    </div>
<% elsif designer_signed_in? %>
    <div class="container text-center"><br><br><br>
        <h1>Welcome <%= current_designer.name %></h1><br><br><br>
        <h4>Use the search bar to look for tags related to the works you are interested in</h4>
        <%= form_for(root_path, remote: true, method: :get) do %>
            <%= text_field_tag :search, params[:search], placeholder: "Enter tag term" %>
            <%= submit_tag "Search" %>
            <br><br>
        <% end %>
        <ul id="search-results"></ul>
    </div>
<% else %>
<div class="container text-center">
    <h1 class="text-center">Looking for a creative SOULMATE?</h1>
    <h2 class="text-center">If you are a music producer or a designer looking to interact, this is your place!</h2>
    <div class="row">
        <div class="col-md-6">
            <h3><%=link_to 'Are you a Producer?', new_producer_registration_path %></h3>
        </div>
        <div class="col-md-6">
            <h3><%=link_to 'Are you a Designer?', new_designer_registration_path %></h3>
        </div>
    </div><br><br>
    <h5>SOME OF THE USERS THAT HAVE BENEFIT FROM CREATIVE SOULMATE:</h5><br><br>
    <div class="card-deck" id="get_api"></div>

    <script>

    </script>
</div>
<% end %>

app/views/home/index.js.erb
var div = document.querySelector('#search-results')

<% elements = @search.map { |search| j render partial: @class_name.downcase, locals: { s: search }} %>

div.innerHTML = "<%= elements.join('').html_safe %>"