config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :work_mates
  resources :track_mates
  resources :works
  resources :tracks


  devise_for :designers, controllers: {
    registrations: 'designers/registrations'
  }
  devise_for :producers, controllers: {
    registrations: 'producers/registrations'
  }
  resources :designers do
    get :pending
    get :works
    get :requested
  end
  resources :producers do
    get :pending
    get :tracks
    get :requested
  end
  root 'home#index'
end

app/models/producer.rb
class Producer < ApplicationRecord
  has_many :tracks, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def to_s
    name
  end
  has_many :work_mates, dependent: :destroy
  has_many :works, through: :work_mates
end

app/controllers/producers/confirmations_controller.rb
# frozen_string_literal: true

class Producers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/producers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Producers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/producers/passwords_controller.rb
# frozen_string_literal: true

class Producers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/producers/registrations_controller.rb
# frozen_string_literal: true

class Producers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/producers/sessions_controller.rb
# frozen_string_literal: true

class Producers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/producers/unlocks_controller.rb
# frozen_string_literal: true

class Producers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  before_action :set_producer, only: %i[ show edit update destroy ]

  # GET /producers or /producers.json
  def index
    @producers = Producer.all
  end

  # GET /producers/1 or /producers/1.json
  def show
  end

  # GET /producers/new
  def new
    @producer = Producer.new
  end

  # GET /producers/1/edit
  def edit
  end

  def tracks
    @tracks = Track.where(producer_id: current_producer.id)
  end

  def requested
    @requested = TrackMate.where(track_id: current_producer.tracks.pluck(:id))
  end

  def pending
    @pending = WorkMate.where(producer_id: current_producer.id, state: "pending")
  end

  # POST /producers or /producers.json
  def create
    @producer = Producer.new(producer_params)

    respond_to do |format|
      if @producer.save
        format.html { redirect_to @producer, notice: "Producer was successfully created." }
        format.json { render :show, status: :created, location: @producer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producers/1 or /producers/1.json
  def update
    respond_to do |format|
      if @producer.update(producer_params)
        format.html { redirect_to @producer, notice: "Producer was successfully updated." }
        format.json { render :show, status: :ok, location: @producer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1 or /producers/1.json
  def destroy
    @producer.destroy
    respond_to do |format|
      format.html { redirect_to producers_url, notice: "Producer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producer
      @producer = Producer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producer_params
      params.require(:producer).permit(:name)
    end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.erb
<%= form_with(model: producer, local: true) do |form| %>
  <% if producer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producer.errors.count, "error") %> prohibited this producer from being saved:</h2>

      <ul>
      <% producer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/producers/edit.html.erb
<h1>Editing Producer</h1>

<%= render 'form', producer: @producer %>

<%= link_to 'Show', @producer %> |
<%= link_to 'Back', producers_path %>

app/views/producers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Producers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @producers.each do |producer| %>
      <tr>
        <td><%= producer.name %></td>
        <td><%= link_to 'Show', producer %></td>
        <td><%= link_to 'Edit', edit_producer_path(producer) %></td>
        <td><%= link_to 'Destroy', producer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producer', new_producer_path %>

app/views/producers/new.html.erb
<h1>New Producer</h1>

<%= render 'form', producer: @producer %>

<%= link_to 'Back', producers_path %>

app/views/producers/pending.html.erb
<p id="notice"><%= notice %></p>

<h1>Pending SoulMates</h1>

<% @pending.each do |pending| %>
<div class="container">
    <ul class="list-unstyled">
    <li> Name: <%=pending.work.work_name  %></li>
    <li>
        <%= image_tag(pending.work.file, width: "40%") %>
    </li>
        <li>From: <%= pending.work.designer %></li>
    </ul>
</div>
<% end %>

app/views/producers/requested.html.erb
<p id="notice"><%= notice %></p>

<h1>My Requested Tracks</h1>

<table>
  <thead>
    <tr>
      <th>My Track</th>
      <th>Requested By</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requested.each do |r| %>
      <tr>
        <td><%= r.track %></td>
        <td><%= r.designer %></td>
        <td><%= r.state %></td>
        <td><%= link_to 'Destroy', r, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/producers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @producer.name %>
</p>

<%= link_to 'Edit', edit_producer_path(@producer) %> |
<%= link_to 'Back', producers_path %>

app/views/producers/tracks.html.erb
<p id="notice"><%= notice %></p>

<h1>My Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Track name</th>
      <th>Producer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.track_name %></td>
        <td><%= track.producer %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>